config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  resources :coins
  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: %i[ new create edit update ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_mining_type_options
    @mining_type_options = MiningType.all.pluck :description, :id
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <p>
    <strong>Description:</strong>
    <%= coin.description %>
  </p>

  <p>
    <strong>Acronym:</strong>
    <%= coin.acronym %>
  </p>

  <p>
    <strong>Url image:</strong>
    <%= coin.url_image %>
  </p>

  <p>
    <strong>Mining Type:</strong>
    <%= coin.mining_type.description %>
  </p>

</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.label :url_image, style: "display: block" %>
    <%= form.text_field :url_image %>
  </div>

  <div>
    <%= form.label :mining_type_id, style: "display: block" %>
    <%= form.select :mining_type_id, @mining_type_options , {include_blank: true} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Show this coin", @coin %> |
  <%= link_to "Back to coins", coins_path %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Coins</h1>

<table id="coins" class="border-collapse table-fixed w-full text-sm">
  <thead class="bg-slate-50 shadow-md">
  <tr>
    <% ["Description", "Acronym", "Image", "Mining Type", "Actions"].each do |e| %>
      <th class="border-b dark:border-slate-600 break-words font-medium text-center p-1 pt-6 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">
        <%= e %>
      </th>
    <% end %>
  </tr>
  </thead>
  <tbody class="bg-white dark:bg-slate-800">
  <% @coins.each do |coin| %>
    <tr>
      <% [coin.description, coin.acronym, image_tag(coin.url_image, width: 25, class: "m-auto"), coin.mining_type.description, link_to("Show this coin", coin)].each do |e| %>
        <td class="border-b border-slate-100 break-words dark:border-slate-700 p-4 px-1 m-auto text-center text-slate-500 dark:text-slate-400">
          <%= e %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "New coin", new_coin_path, class: "float-right pt-6 mr-3 font-bold underline" %>

app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Back to coins", coins_path %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
  <%= link_to "Edit this coin", edit_coin_path(@coin) %> |
  <%= link_to "Back to coins", coins_path %>

  <%= button_to "Destroy this coin", @coin, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CryptoWallet</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
</head>

<body class="bg-slate-50 text-slate-900">
<header class="w-100 p-5 flex justify-between shadow-md">
  <strong class="block text-lg">
    <%= link_to "CryptoWallet", "/" %>
  </strong>
  <div>
    <ul class="flex gap-5">
      <li>
        <%= link_to "Coins", coins_path %>
      </li>
      <li>
        <%= link_to "Mining Types", mining_types_path %>
      </li>
    </ul>
  </div>
</header>
<main class="container mx-auto mt-28 px-5">
  <%= yield %>
</main>
</body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <p>
    <strong>Description:</strong>
    <%= mining_type.description %>
  </p>

  <p>
    <strong>Acronym:</strong>
    <%= mining_type.acronym %>
  </p>

</div>

app/views/mining_types/edit.html.erb
<h1>Editing mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Show this mining type", @mining_type %> |
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mining types</h1>

<table id="mining_types" class="border-collapse table-fixed w-full text-sm">
  <thead class="bg-slate-50 shadow-md">
  <tr>
    <% %w[Description Acronym Actions].each do |e| %>
      <th class="border-b dark:border-slate-600 break-words font-medium text-center p-1 pt-6 pt-0 pb-3 text-slate-400 dark:text-slate-200 text-left">
        <%= e %>
      </th>
    <% end %>
  </tr>
  </thead>
  <tbody class="bg-white dark:bg-slate-800">
  <% @mining_types.each do |miningType| %>
    <tr>
      <% [miningType.description, miningType.acronym, link_to("Show this coin", miningType)].each do |e| %>
        <td class="border-b border-slate-100 break-words dark:border-slate-700 p-4 px-1 m-auto text-center text-slate-500 dark:text-slate-400">
          <%= e %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "New Mining Type", new_mining_type_path, class: "float-right pt-6 mr-3 font-bold underline" %>

app/views/mining_types/new.html.erb
<h1>New mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>

<div>
  <%= link_to "Edit this mining type", edit_mining_type_path(@mining_type) %> |
  <%= link_to "Back to mining types", mining_types_path %>

  <%= button_to "Destroy this mining type", @mining_type, method: :delete %>
</div>

app/views/welcome/index.html.erb
<p class="text-3xl font-bold underline">Hello world!</p>